version: '3.8'
services:
  ruby_app:
    container_name: ruby_app
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - test_postgres
      - test_redis
    networks:
      ruby_network:
        aliases:
          - test_redis
          - test_postgres

  test_redis:
    image: 'redis:latest'
    container_name: test_redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - test_redis:/bitnami/redis/data
    networks:
      bridge:
      ruby_network:

  test_postgres:
    image: 'postgres:latest'
    restart: always
    container_name: test_postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      PGDATA: /var/lib/postgresql/test/data
    volumes:
      - test_postgres_db:/var/lib/postgresql/test/data
    ports:
      - "${PG_STREAMING_PORT:-5432}:5432"
    networks:
      bridge:
      ruby_network:

volumes:
  test_redis:
  test_postgres_db:


networks:
  bridge:
  ruby_network:
    name: ruby_network